providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd Project/app", "pip install -r requirements.txt"]

[start]
cmd = "cd Project/app && gunicorn --config gunicorn.conf.py app:app"
