providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd Project/app",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --config gunicorn.conf.py app:app"
workDir = "Project/app"
