services:
  - type: web
    name: malware-detection
    env: python
    pythonVersion: 3.11.9
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
